//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Motion_Designer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WAVE_TimeScaleIndex {
            get {
                return ((int)(this["WAVE_TimeScaleIndex"]));
            }
            set {
                this["WAVE_TimeScaleIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WAVE_TimeMeasView {
            get {
                return ((bool)(this["WAVE_TimeMeasView"]));
            }
            set {
                this["WAVE_TimeMeasView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WAVE_TrgEnable {
            get {
                return ((bool)(this["WAVE_TrgEnable"]));
            }
            set {
                this["WAVE_TrgEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color WAVE_WindowColor {
            get {
                return ((global::System.Drawing.Color)(this["WAVE_WindowColor"]));
            }
            set {
                this["WAVE_WindowColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkOliveGreen")]
        public global::System.Drawing.Color WAVE_TimeScaleColor {
            get {
                return ((global::System.Drawing.Color)(this["WAVE_TimeScaleColor"]));
            }
            set {
                this["WAVE_TimeScaleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color WAVE_InposColor {
            get {
                return ((global::System.Drawing.Color)(this["WAVE_InposColor"]));
            }
            set {
                this["WAVE_InposColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float WAVE_PosLineSize {
            get {
                return ((float)(this["WAVE_PosLineSize"]));
            }
            set {
                this["WAVE_PosLineSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public global::System.Drawing.Drawing2D.DashStyle WAVE_PosLineType {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["WAVE_PosLineType"]));
            }
            set {
                this["WAVE_PosLineType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cyan")]
        public global::System.Drawing.Color WAVE_PosColor {
            get {
                return ((global::System.Drawing.Color)(this["WAVE_PosColor"]));
            }
            set {
                this["WAVE_PosColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CornflowerBlue")]
        public global::System.Drawing.Color WAVE_VelColor {
            get {
                return ((global::System.Drawing.Color)(this["WAVE_VelColor"]));
            }
            set {
                this["WAVE_VelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pink")]
        public global::System.Drawing.Color WAVE_CurColor {
            get {
                return ((global::System.Drawing.Color)(this["WAVE_CurColor"]));
            }
            set {
                this["WAVE_CurColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float WAVE_VelLineSize {
            get {
                return ((float)(this["WAVE_VelLineSize"]));
            }
            set {
                this["WAVE_VelLineSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public global::System.Drawing.Drawing2D.DashStyle WAVE_VelLineType {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["WAVE_VelLineType"]));
            }
            set {
                this["WAVE_VelLineType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float WAVE_CurLineSize {
            get {
                return ((float)(this["WAVE_CurLineSize"]));
            }
            set {
                this["WAVE_CurLineSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public global::System.Drawing.Drawing2D.DashStyle WAVE_CurLineType {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["WAVE_CurLineType"]));
            }
            set {
                this["WAVE_CurLineType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-6")]
        public int WAVE_InposOffset {
            get {
                return ((int)(this["WAVE_InposOffset"]));
            }
            set {
                this["WAVE_InposOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float WAVE_InposLineSize {
            get {
                return ((float)(this["WAVE_InposLineSize"]));
            }
            set {
                this["WAVE_InposLineSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public global::System.Drawing.Drawing2D.DashStyle WAVE_InposLineType {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["WAVE_InposLineType"]));
            }
            set {
                this["WAVE_InposLineType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WAVE_PosView {
            get {
                return ((bool)(this["WAVE_PosView"]));
            }
            set {
                this["WAVE_PosView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WAVE_VelView {
            get {
                return ((bool)(this["WAVE_VelView"]));
            }
            set {
                this["WAVE_VelView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WAVE_InposView {
            get {
                return ((bool)(this["WAVE_InposView"]));
            }
            set {
                this["WAVE_InposView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WAVE_CurView {
            get {
                return ((bool)(this["WAVE_CurView"]));
            }
            set {
                this["WAVE_CurView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WAVE_ItemY_L_View {
            get {
                return ((bool)(this["WAVE_ItemY_L_View"]));
            }
            set {
                this["WAVE_ItemY_L_View"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GreenYellow")]
        public global::System.Drawing.Color WAVE_TimeMeasColor {
            get {
                return ((global::System.Drawing.Color)(this["WAVE_TimeMeasColor"]));
            }
            set {
                this["WAVE_TimeMeasColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float WAVE_TimeMeasLineSize {
            get {
                return ((float)(this["WAVE_TimeMeasLineSize"]));
            }
            set {
                this["WAVE_TimeMeasLineSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dot")]
        public global::System.Drawing.Drawing2D.DashStyle WAVE_TimeMeasLineType {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["WAVE_TimeMeasLineType"]));
            }
            set {
                this["WAVE_TimeMeasLineType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int WAVE_P_Div {
            get {
                return ((int)(this["WAVE_P_Div"]));
            }
            set {
                this["WAVE_P_Div"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int WAVE_V_Div {
            get {
                return ((int)(this["WAVE_V_Div"]));
            }
            set {
                this["WAVE_V_Div"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int WAVE_I_Div {
            get {
                return ((int)(this["WAVE_I_Div"]));
            }
            set {
                this["WAVE_I_Div"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int WAVE_T_DIV {
            get {
                return ((int)(this["WAVE_T_DIV"]));
            }
            set {
                this["WAVE_T_DIV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WAVE_TimeScaleView {
            get {
                return ((bool)(this["WAVE_TimeScaleView"]));
            }
            set {
                this["WAVE_TimeScaleView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WAVE_ItemY_R_View {
            get {
                return ((bool)(this["WAVE_ItemY_R_View"]));
            }
            set {
                this["WAVE_ItemY_R_View"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5")]
        public int WAVE_CmdposOffset {
            get {
                return ((int)(this["WAVE_CmdposOffset"]));
            }
            set {
                this["WAVE_CmdposOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WAVE_CmdposView {
            get {
                return ((bool)(this["WAVE_CmdposView"]));
            }
            set {
                this["WAVE_CmdposView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float WAVE_CmdposLineSize {
            get {
                return ((float)(this["WAVE_CmdposLineSize"]));
            }
            set {
                this["WAVE_CmdposLineSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public global::System.Drawing.Drawing2D.DashStyle WAVE_CmdposLineType {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["WAVE_CmdposLineType"]));
            }
            set {
                this["WAVE_CmdposLineType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color WAVE_CmdposColor {
            get {
                return ((global::System.Drawing.Color)(this["WAVE_CmdposColor"]));
            }
            set {
                this["WAVE_CmdposColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Crimson")]
        public global::System.Drawing.Color WAVE_TrgColor {
            get {
                return ((global::System.Drawing.Color)(this["WAVE_TrgColor"]));
            }
            set {
                this["WAVE_TrgColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float WAVE_TrgLineSize {
            get {
                return ((float)(this["WAVE_TrgLineSize"]));
            }
            set {
                this["WAVE_TrgLineSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dash")]
        public global::System.Drawing.Drawing2D.DashStyle WAVE_TrgLineType {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["WAVE_TrgLineType"]));
            }
            set {
                this["WAVE_TrgLineType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float WAVE_TimeScaleLineSize {
            get {
                return ((float)(this["WAVE_TimeScaleLineSize"]));
            }
            set {
                this["WAVE_TimeScaleLineSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public global::System.Drawing.Drawing2D.DashStyle WAVE_TimeScaleLineType {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["WAVE_TimeScaleLineType"]));
            }
            set {
                this["WAVE_TimeScaleLineType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WAVE_TrgPosition {
            get {
                return ((int)(this["WAVE_TrgPosition"]));
            }
            set {
                this["WAVE_TrgPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color WAVE_Prm1Color {
            get {
                return ((global::System.Drawing.Color)(this["WAVE_Prm1Color"]));
            }
            set {
                this["WAVE_Prm1Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public global::System.Drawing.Drawing2D.DashStyle WAVE_Prm1LineType {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["WAVE_Prm1LineType"]));
            }
            set {
                this["WAVE_Prm1LineType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color WAVE_Prm2Color {
            get {
                return ((global::System.Drawing.Color)(this["WAVE_Prm2Color"]));
            }
            set {
                this["WAVE_Prm2Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float WAVE_Prm1LineSize {
            get {
                return ((float)(this["WAVE_Prm1LineSize"]));
            }
            set {
                this["WAVE_Prm1LineSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float WAVE_Prm2LineSize {
            get {
                return ((float)(this["WAVE_Prm2LineSize"]));
            }
            set {
                this["WAVE_Prm2LineSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public global::System.Drawing.Drawing2D.DashStyle WAVE_Prm2LineType {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["WAVE_Prm2LineType"]));
            }
            set {
                this["WAVE_Prm2LineType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color WAVE_Prm3Color {
            get {
                return ((global::System.Drawing.Color)(this["WAVE_Prm3Color"]));
            }
            set {
                this["WAVE_Prm3Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float WAVE_Prm3LineSize {
            get {
                return ((float)(this["WAVE_Prm3LineSize"]));
            }
            set {
                this["WAVE_Prm3LineSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public global::System.Drawing.Drawing2D.DashStyle WAVE_Prm3LineType {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["WAVE_Prm3LineType"]));
            }
            set {
                this["WAVE_Prm3LineType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WAVE_Prm1View {
            get {
                return ((bool)(this["WAVE_Prm1View"]));
            }
            set {
                this["WAVE_Prm1View"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WAVE_Prm2View {
            get {
                return ((bool)(this["WAVE_Prm2View"]));
            }
            set {
                this["WAVE_Prm2View"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WAVE_Prm3View {
            get {
                return ((bool)(this["WAVE_Prm3View"]));
            }
            set {
                this["WAVE_Prm3View"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int WAVE_Prm1_Div {
            get {
                return ((int)(this["WAVE_Prm1_Div"]));
            }
            set {
                this["WAVE_Prm1_Div"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int WAVE_Prm2_Div {
            get {
                return ((int)(this["WAVE_Prm2_Div"]));
            }
            set {
                this["WAVE_Prm2_Div"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int WAVE_Prm3_Div {
            get {
                return ((int)(this["WAVE_Prm3_Div"]));
            }
            set {
                this["WAVE_Prm3_Div"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CollapseLayout {
            get {
                return ((bool)(this["CollapseLayout"]));
            }
            set {
                this["CollapseLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ViewOpenDrive {
            get {
                return ((bool)(this["ViewOpenDrive"]));
            }
            set {
                this["ViewOpenDrive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ThisLayout {
            get {
                return ((int)(this["ThisLayout"]));
            }
            set {
                this["ThisLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WAVE_ViewSetting_View {
            get {
                return ((bool)(this["WAVE_ViewSetting_View"]));
            }
            set {
                this["WAVE_ViewSetting_View"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PASSWORD_LOCK {
            get {
                return ((bool)(this["PASSWORD_LOCK"]));
            }
            set {
                this["PASSWORD_LOCK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CLOSE_MSG_DISABLE {
            get {
                return ((bool)(this["CLOSE_MSG_DISABLE"]));
            }
            set {
                this["CLOSE_MSG_DISABLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CultureType {
            get {
                return ((string)(this["CultureType"]));
            }
            set {
                this["CultureType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal MainTimerInterval {
            get {
                return ((decimal)(this["MainTimerInterval"]));
            }
            set {
                this["MainTimerInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal LogPeriod {
            get {
                return ((decimal)(this["LogPeriod"]));
            }
            set {
                this["LogPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public float WAVE_XScale {
            get {
                return ((float)(this["WAVE_XScale"]));
            }
            set {
                this["WAVE_XScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int LogTime {
            get {
                return ((int)(this["LogTime"]));
            }
            set {
                this["LogTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public float WAVE_YScale {
            get {
                return ((float)(this["WAVE_YScale"]));
            }
            set {
                this["WAVE_YScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float WAVE_P_Mul {
            get {
                return ((float)(this["WAVE_P_Mul"]));
            }
            set {
                this["WAVE_P_Mul"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float WAVE_V_Mul {
            get {
                return ((float)(this["WAVE_V_Mul"]));
            }
            set {
                this["WAVE_V_Mul"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float WAVE_I_Mul {
            get {
                return ((float)(this["WAVE_I_Mul"]));
            }
            set {
                this["WAVE_I_Mul"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float WAVE_Prm1_Mul {
            get {
                return ((float)(this["WAVE_Prm1_Mul"]));
            }
            set {
                this["WAVE_Prm1_Mul"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float WAVE_Prm2_Mul {
            get {
                return ((float)(this["WAVE_Prm2_Mul"]));
            }
            set {
                this["WAVE_Prm2_Mul"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float WAVE_Prm3_Mul {
            get {
                return ((float)(this["WAVE_Prm3_Mul"]));
            }
            set {
                this["WAVE_Prm3_Mul"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float WAVE_P_Pos {
            get {
                return ((float)(this["WAVE_P_Pos"]));
            }
            set {
                this["WAVE_P_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float WAVE_V_Pos {
            get {
                return ((float)(this["WAVE_V_Pos"]));
            }
            set {
                this["WAVE_V_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float WAVE_I_Pos {
            get {
                return ((float)(this["WAVE_I_Pos"]));
            }
            set {
                this["WAVE_I_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float WAVE_Prm1_Pos {
            get {
                return ((float)(this["WAVE_Prm1_Pos"]));
            }
            set {
                this["WAVE_Prm1_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float WAVE_Prm2_Pos {
            get {
                return ((float)(this["WAVE_Prm2_Pos"]));
            }
            set {
                this["WAVE_Prm2_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float WAVE_Prm3_Pos {
            get {
                return ((float)(this["WAVE_Prm3_Pos"]));
            }
            set {
                this["WAVE_Prm3_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WAVE_BackupHeight {
            get {
                return ((int)(this["WAVE_BackupHeight"]));
            }
            set {
                this["WAVE_BackupHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PASSWORD_TEMP {
            get {
                return ((bool)(this["PASSWORD_TEMP"]));
            }
            set {
                this["PASSWORD_TEMP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PASSWORD_TRI {
            get {
                return ((bool)(this["PASSWORD_TRI"]));
            }
            set {
                this["PASSWORD_TRI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WAVE_Pos_Idx {
            get {
                return ((int)(this["WAVE_Pos_Idx"]));
            }
            set {
                this["WAVE_Pos_Idx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int WAVE_Vel_Idx {
            get {
                return ((int)(this["WAVE_Vel_Idx"]));
            }
            set {
                this["WAVE_Vel_Idx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int WAVE_Cur_Idx {
            get {
                return ((int)(this["WAVE_Cur_Idx"]));
            }
            set {
                this["WAVE_Cur_Idx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WAVE_Prm1_Idx {
            get {
                return ((int)(this["WAVE_Prm1_Idx"]));
            }
            set {
                this["WAVE_Prm1_Idx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WAVE_Prm2_Idx {
            get {
                return ((int)(this["WAVE_Prm2_Idx"]));
            }
            set {
                this["WAVE_Prm2_Idx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WAVE_Prm3_Idx {
            get {
                return ((int)(this["WAVE_Prm3_Idx"]));
            }
            set {
                this["WAVE_Prm3_Idx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DEV_CON_ENABLE {
            get {
                return ((bool)(this["DEV_CON_ENABLE"]));
            }
            set {
                this["DEV_CON_ENABLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PASSWORD_HIKARI {
            get {
                return ((bool)(this["PASSWORD_HIKARI"]));
            }
            set {
                this["PASSWORD_HIKARI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PASSWORD_KASHIYAMA {
            get {
                return ((bool)(this["PASSWORD_KASHIYAMA"]));
            }
            set {
                this["PASSWORD_KASHIYAMA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PASSWORD_AMADA {
            get {
                return ((bool)(this["PASSWORD_AMADA"]));
            }
            set {
                this["PASSWORD_AMADA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PASSWORD_TAD8821 {
            get {
                return ((bool)(this["PASSWORD_TAD8821"]));
            }
            set {
                this["PASSWORD_TAD8821"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WAVE_AlarmAutoStop {
            get {
                return ((bool)(this["WAVE_AlarmAutoStop"]));
            }
            set {
                this["WAVE_AlarmAutoStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PASSWORD_AMADATEST {
            get {
                return ((bool)(this["PASSWORD_AMADATEST"]));
            }
            set {
                this["PASSWORD_AMADATEST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string COMPort {
            get {
                return ((string)(this["COMPort"]));
            }
            set {
                this["COMPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Cycle {
            get {
                return ((int)(this["Cycle"]));
            }
            set {
                this["Cycle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TSM3510N8060,94,500,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,100")]
        public string Inspection1 {
            get {
                return ((string)(this["Inspection1"]));
            }
            set {
                this["Inspection1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TSM2261N9030,75,500,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,100")]
        public string Inspection2 {
            get {
                return ((string)(this["Inspection2"]));
            }
            set {
                this["Inspection2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0")]
        public string Inspection3 {
            get {
                return ((string)(this["Inspection3"]));
            }
            set {
                this["Inspection3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0")]
        public string Inspection4 {
            get {
                return ((string)(this["Inspection4"]));
            }
            set {
                this["Inspection4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0")]
        public string Inspection5 {
            get {
                return ((string)(this["Inspection5"]));
            }
            set {
                this["Inspection5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0")]
        public string Inspection6 {
            get {
                return ((string)(this["Inspection6"]));
            }
            set {
                this["Inspection6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0")]
        public string Inspection7 {
            get {
                return ((string)(this["Inspection7"]));
            }
            set {
                this["Inspection7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0")]
        public string Inspection8 {
            get {
                return ((string)(this["Inspection8"]));
            }
            set {
                this["Inspection8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0")]
        public string Inspection9 {
            get {
                return ((string)(this["Inspection9"]));
            }
            set {
                this["Inspection9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0")]
        public string Inspection10 {
            get {
                return ((string)(this["Inspection10"]));
            }
            set {
                this["Inspection10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MotorDir {
            get {
                return ((int)(this["MotorDir"]));
            }
            set {
                this["MotorDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int NumberFiles {
            get {
                return ((int)(this["NumberFiles"]));
            }
            set {
                this["NumberFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\osm-server\\sqlexspress,HD_2014,sa,tamagawa")]
        public string DataBase {
            get {
                return ((string)(this["DataBase"]));
            }
            set {
                this["DataBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TSM3510N8060,1000,4324,1000,3603,4325,3603,5.5,10.0")]
        public string Photo1 {
            get {
                return ((string)(this["Photo1"]));
            }
            set {
                this["Photo1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TSM2261N9030,1000,1688,1000,1583,1688,1583,8.5,12.0")]
        public string Photo2 {
            get {
                return ((string)(this["Photo2"]));
            }
            set {
                this["Photo2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",0,0,0,0,0,0,0.00,0.00")]
        public string Photo3 {
            get {
                return ((string)(this["Photo3"]));
            }
            set {
                this["Photo3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",0,0,0,0,0,0,0.00,0.00")]
        public string Photo4 {
            get {
                return ((string)(this["Photo4"]));
            }
            set {
                this["Photo4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",0,0,0,0,0,0,0.00,0.00")]
        public string Photo5 {
            get {
                return ((string)(this["Photo5"]));
            }
            set {
                this["Photo5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",0,0,0,0,0,0,0.00,0.00")]
        public string Photo6 {
            get {
                return ((string)(this["Photo6"]));
            }
            set {
                this["Photo6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",0,0,0,0,0,0,0.00,0.00")]
        public string Photo7 {
            get {
                return ((string)(this["Photo7"]));
            }
            set {
                this["Photo7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",0,0,0,0,0,0,0.00,0.00")]
        public string Photo8 {
            get {
                return ((string)(this["Photo8"]));
            }
            set {
                this["Photo8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",0,0,0,0,0,0,0.00,0.00")]
        public string Photo9 {
            get {
                return ((string)(this["Photo9"]));
            }
            set {
                this["Photo9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",0,0,0,0,0,0,0.00,0.00")]
        public string Photo10 {
            get {
                return ((string)(this["Photo10"]));
            }
            set {
                this["Photo10"] = value;
            }
        }
    }
}
